name: CI # 自动部署的名称
on:
  push:
    branches: # 当提交master代码 则触发自动部署到服务端 如 git push main
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤
    # 第一步：下载源码（CI/CD拉取代码到自己的本地）
    - name: Checkout
      uses: actions/checkout@master

    # 第二步：打包构建
    - name: Build
      uses: actions/setup-node@master
      with:
        node-version: '18.17.x'
    - run: npm ci # 安装第三方包
    - run: npm run build # 打包

    # 第三步：部署到服务器
    - name: Deploy
      uses: easingthemes/ssh-deploy@main # 使用ssh部署
      with:
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_PORT: ${{ secrets.PORT }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SOURCE: dist
        TARGET: ${{ secrets.REMOTE_TARGET }}
